// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Supabase is properly configured
const isSupabaseConfigured = import.meta.env.VITE_SUPABASE_URL && 
                            import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY &&
                            !import.meta.env.VITE_SUPABASE_URL.includes('placeholder') &&
                            !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY.includes('placeholder') &&
                            !import.meta.env.VITE_SUPABASE_URL.includes('your-project');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false, // Disable session persistence to avoid token refresh errors
    autoRefreshToken: false, // Disable auto refresh to prevent network errors
  }
});

// Export configuration status for components to check
export const isSupabaseReady = isSupabaseConfigured;